language: cpp

jobs:
  include:
  - stage: build
    os: Windows
    compiler: clang
    dist: trusty
    addons:
        apt:
            packages:
                - cmake
    script:
        - mkdir build
        - cmake -S ./ -B ./build -A x64
        - cmake --build ./build --config Release
        
  - stage: build
    os: Windows
    compiler: gcc
    dist: trusty
    addons:
        apt:
            packages:
                - cmake
    script:
        - mkdir build
        - cmake -S ./ -B ./build -A x64
        - cmake --build ./build --config Release
        
  - stage: build
    os: Linux
    compiler: clang
    dist: trusty
    addons:
        apt:
            packages:
                - cmake
    script:
        - mkdir build
        - cd ./build
        - cmake .. -A x64
        - cmake --build . --config Release
        
  - stage: build
    os: Linux
    compiler: gcc
    dist: trusty
    addons:
        apt:
            packages:
                - cmake
    script:
        - mkdir build
        - cd ./build
        - cmake .. -A x64
        - cmake --build . --config Release
        
  - stage: build
    os: osx
    compiler: clang
    osx_image: xcode11.3
    addons:
        apt:
            packages:
                - cmake
    script:
        - mkdir build
        - cmake -S ./ -B ./build
        - cmake --build ./build --config Release
        
  - stage: build
    os: osx
    compiler: gcc
    osx_image: xcode11.3
    addons:
        apt:
            packages:
                - cmake
    script:
        - mkdir build
        - cmake -S ./ -B ./build
        - cmake --build ./build --config Release