dist: trusty

language: cpp
os:
    - Windows
        
compiler:
    - clang
    - gcc
   
addons:
    apt:
        
        packages:
            - cmake
            
script:
    - mkdir build
    - cmake -S . -B ./build -A x64
    - cmake --build ./build --target Rescan
    - cmake --build ./build