
language: cpp

compiler:
    - clang
    - gcc

jobs:
    include:
    - stage: build
        os: Windows
        dist: trusty
        addons:
            apt:
               packages:
                    - cmake
        script:
        - mkdir build
        - cmake -S ./ -B ./build -A x64
        - cmake --build ./build --config Release
        
    - stage: build
        os: Linux
        dist: trusty
        addons:
            apt:
               packages:
                    - cmake
        script:
        - mkdir build
        - cmake -S ./ -B ./build -A x64
        - cmake --build ./build --config Release
        
    - stage: build
        os: osx
        dist: trusty
        addons:
            apt:
               packages:
                    - cmake
        script:
        - mkdir build
        - cmake -S ./ -B ./build
        - cmake --build ./build --config Release