dist: trusty

language: cpp
compiler:
    - clang
    - gcc
    
addons:
    apt:
        packages:
            - cmake

matrix:
    include:
    - os: Windows
        script:
        - mkdir build
        - cmake -S ./ -B ./build -A x64
        - cmake --build ./build --config Release
        
    - os: Linux
        script:
        - mkdir build
        - cmake -S ./ -B ./build -A x64
        - cmake --build ./build --config Release

    - os: osx
        script:
        - mkdir build
        - cmake -S ./ -B ./build
        - cmake --build ./build --config Release